/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface FontIcon {
        "config": any;
        "icon": string;
    }
    interface IntButton {
        "logoImage": string;
    }
    interface IntNavbar {
        "logoImage": string;
    }
    interface IntSideitem {
    }
    interface IntSidenav {
    }
}
declare global {
    interface HTMLFontIconElement extends Components.FontIcon, HTMLStencilElement {
    }
    var HTMLFontIconElement: {
        prototype: HTMLFontIconElement;
        new (): HTMLFontIconElement;
    };
    interface HTMLIntButtonElement extends Components.IntButton, HTMLStencilElement {
    }
    var HTMLIntButtonElement: {
        prototype: HTMLIntButtonElement;
        new (): HTMLIntButtonElement;
    };
    interface HTMLIntNavbarElement extends Components.IntNavbar, HTMLStencilElement {
    }
    var HTMLIntNavbarElement: {
        prototype: HTMLIntNavbarElement;
        new (): HTMLIntNavbarElement;
    };
    interface HTMLIntSideitemElement extends Components.IntSideitem, HTMLStencilElement {
    }
    var HTMLIntSideitemElement: {
        prototype: HTMLIntSideitemElement;
        new (): HTMLIntSideitemElement;
    };
    interface HTMLIntSidenavElement extends Components.IntSidenav, HTMLStencilElement {
    }
    var HTMLIntSidenavElement: {
        prototype: HTMLIntSidenavElement;
        new (): HTMLIntSidenavElement;
    };
    interface HTMLElementTagNameMap {
        "font-icon": HTMLFontIconElement;
        "int-button": HTMLIntButtonElement;
        "int-navbar": HTMLIntNavbarElement;
        "int-sideitem": HTMLIntSideitemElement;
        "int-sidenav": HTMLIntSidenavElement;
    }
}
declare namespace LocalJSX {
    interface FontIcon {
        "config"?: any;
        "icon"?: string;
    }
    interface IntButton {
        "logoImage"?: string;
    }
    interface IntNavbar {
        "logoImage"?: string;
    }
    interface IntSideitem {
    }
    interface IntSidenav {
    }
    interface IntrinsicElements {
        "font-icon": FontIcon;
        "int-button": IntButton;
        "int-navbar": IntNavbar;
        "int-sideitem": IntSideitem;
        "int-sidenav": IntSidenav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "font-icon": LocalJSX.FontIcon & JSXBase.HTMLAttributes<HTMLFontIconElement>;
            "int-button": LocalJSX.IntButton & JSXBase.HTMLAttributes<HTMLIntButtonElement>;
            "int-navbar": LocalJSX.IntNavbar & JSXBase.HTMLAttributes<HTMLIntNavbarElement>;
            "int-sideitem": LocalJSX.IntSideitem & JSXBase.HTMLAttributes<HTMLIntSideitemElement>;
            "int-sidenav": LocalJSX.IntSidenav & JSXBase.HTMLAttributes<HTMLIntSidenavElement>;
        }
    }
}
