/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IntButton {
    }
}
declare global {
    interface HTMLIntButtonElement extends Components.IntButton, HTMLStencilElement {
    }
    var HTMLIntButtonElement: {
        prototype: HTMLIntButtonElement;
        new (): HTMLIntButtonElement;
    };
    interface HTMLElementTagNameMap {
        "int-button": HTMLIntButtonElement;
    }
}
declare namespace LocalJSX {
    interface IntButton {
    }
    interface IntrinsicElements {
        "int-button": IntButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "int-button": LocalJSX.IntButton & JSXBase.HTMLAttributes<HTMLIntButtonElement>;
        }
    }
}
